spring.application.name=micro-backend
app.upload.directory=uploads
app.upload.result-directory=result
app.separation.enabled=true
app.separation.python-executable=.venv-win/Scripts/python.exe
app.separation.script-path=separate_audio.py
app.separation.model-id=speechbrain/sepformer-libri3mix
app.separation.model-cache-directory=model-cache/sepformer-libri3mix
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
